version: '3'

services:
  kafka:
    image: bitnami/kafka
    ports:
      - "9092:9092"

  producer:
    build:
      context: .
      dockerfile: producer/Dockerfile
    ports:
      - "9093:9092"

  consumer:
    build:
      context: .
      dockerfile: consumer/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - producer