version: '3'

services:
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka-network

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    networks:
      - kafka-network
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test:1:1"
    depends_on:
      - zookeeper

  producer:
    build:
      context: .
      dockerfile: producer/Dockerfile
    ports:
      - "9093:9092"
    networks:
      - kafka-network
    depends_on:
      - kafka

  consumer:
    build:
      context: .
      dockerfile: consumer-py/Dockerfile
    ports:
      - "3000:3000"
    networks:
      - kafka-network
    depends_on:
      - producer

networks:
  kafka-network:
    driver: bridge
